# Generated by Django 5.2.16 on 2026-07-15 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('folder', 'Server folder path'), ('upload', 'Uploaded images')], max_length=10)),
                ('folder_path', models.CharField(blank=True, max_length=500)),
                ('resize_width', models.PositiveIntegerField(blank=True, null=True)),
                ('resize_height', models.PositiveIntegerField(blank=True, null=True)),
                ('normalize', models.BooleanField(default=False)),
                ('max_images', models.PositiveIntegerField(blank=True, help_text="Only used for 'Server folder path' datasets — 0/blank = load all.", null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('framework', models.CharField(choices=[('tensorflow', 'TensorFlow / Keras (.h5 / .keras)'), ('pytorch', 'PyTorch (.pt / .pth — full saved model)'), ('sklearn', 'scikit-learn (.pkl / .joblib)'), ('onnx', 'ONNX (.onnx)')], max_length=20)),
                ('model_file', models.FileField(upload_to='models/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='datasets/%Y/%m/%d/')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='robustness.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('regression', 'Regression'), ('classification', 'Classification')], default='regression', max_length=20)),
                ('range_threshold', models.FloatField(default=5.0)),
                ('max_samples', models.PositiveIntegerField(default=10)),
                ('samples_per_mr', models.PositiveIntegerField(default=5)),
                ('show_progress', models.BooleanField(default=True)),
                ('verbose', models.BooleanField(default=True)),
                ('epsilon_min', models.FloatField(default=0.01)),
                ('epsilon_max', models.FloatField(default=0.2)),
                ('epsilon_count', models.PositiveIntegerField(default=4)),
                ('selected_mrs', models.JSONField(default=list)),
                ('output_dir', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('runtime_seconds', models.FloatField(blank=True, null=True)),
                ('console_log', models.TextField(blank=True)),
                ('transforms', models.JSONField(blank=True, null=True)),
                ('relations', models.JSONField(blank=True, null=True)),
                ('sample_prediction', models.CharField(blank=True, max_length=200)),
                ('dataset_size', models.PositiveIntegerField(blank=True, null=True)),
                ('pickle_ok', models.BooleanField(blank=True, null=True)),
                ('pickle_err', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('traceback_text', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='robustness.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='robustness.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
