# Generated by Django 5.2.16 on 2026-07-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robustness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_webcam_url', models.CharField(blank=True, help_text='e.g. http://192.168.1.23:8080 (no trailing slash, no /shot.jpg)', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera settings',
                'verbose_name_plural': 'Camera settings',
            },
        ),
    ]
